name: Workflow

'on':
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: null

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: List contents
        run: ls

      - name: Compile classes
        working-directory: ./src
        run: |
          javac -cp "../testresources/junit-platform-console-standalone-1.6.0.jar" registrationasignment_new/registrationasignment_new.java packageName/Login.java packageName/Task.java ../test/registrationasignment_new/TaskTest.java
      - name: List contents of src directory after compile
        working-directory: ./src/registrationasignment_new
        run: ls

      - name: Create testresources/registrationasignment_new directory
        run: mkdir -p ./testresources/registrationasignment_new

      - name: Copy compiled classes to testresources directory
        run: cp ./src/registrationasignment_new/registrationasignment_new.class ./src/packageName/Login.class ./src/packageName/Task.class ./testresources/registrationasignment_new/

      - name: Copy compiled Test classes to testresources directory
        run: cp ./test/registrationasignment_new/TaskTest.class ./testresources/registrationasignment_new/

      - name: List contents of testresources/registrationasignment_new directory
        run: ls ./testresources/registrationasignment_new
